apiVersion: v1
kind: Service
metadata:
  name: app-nodeport-service
  labels:
    app: color-api
    tier: service

spec:
  type: NodePort
  selector:
    app: color-api
    tier: backend

  ports:
    - port: 80
