apiVersion: v1
kind: Secret
metadata:
  name: db-app-user-secret
  labels:
    app: color-api
    tier: secret

data:
  MONGODB_INITDB_DATABASE: Y29sb3Jz
  INITDB_USER: Y29sb3JzLXVzZXI=
  INITDB_USER_PASSWORD: Y29sb3JzLXVzZXItcGFzc3dvcmQ=
