apiVersion: v1
kind: Secret
metadata:
  name: db-root-user-secret
  labels:
    app: color-api
    tier: secret

data:
  MONGODB_INITDB_ROOT_USERNAME: cm9vdA==
  MONGODB_INITDB_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
